@echo off
setlocal

set "CHROMALINK_HTTP_BRIDGE_URL=%CHROMALINK_HTTP_BRIDGE_URL%"
if not defined CHROMALINK_HTTP_BRIDGE_URL set "CHROMALINK_HTTP_BRIDGE_URL=http://127.0.0.1:7337/"

start "" "%CHROMALINK_HTTP_BRIDGE_URL%"
exit /b %ERRORLEVEL%
