@echo off
setlocal

set "CHROMALINK_HTTP_BRIDGE_URL=%CHROMALINK_HTTP_BRIDGE_URL%"
if not defined CHROMALINK_HTTP_BRIDGE_URL set "CHROMALINK_HTTP_BRIDGE_URL=http://127.0.0.1:7337/"
set "CHROMALINK_HTTP_BRIDGE_OPEN_TARGET=%CHROMALINK_HTTP_BRIDGE_OPEN_TARGET%"
if not defined CHROMALINK_HTTP_BRIDGE_OPEN_TARGET set "CHROMALINK_HTTP_BRIDGE_OPEN_TARGET="

start "" /min "%CHROMALINK_HTTP_BRIDGE_URL%%CHROMALINK_HTTP_BRIDGE_OPEN_TARGET%"
exit /b %ERRORLEVEL%
